### ISSUE TITLE
🪲 Bug Report - Deploy Custom Policy Definitions fails with "The policy set definition 'Deploy-Diagnostics-x' request is invalid

### ISSUE THREAD

**Issue by janegilring** [Azure/ALZ-Bicep#399]
## Describe the bug

I have [forked](https://github.com/janegilring/ALZ-Bicep/tree/msft-demo-contoso) the latest ALZ-Bicep code (per 2022-11-26) and created a custom branch for setting up a demo environment.
A GitHub Actions workflow is configured based on [this](https://github.com/Azure/ALZ-Bicep/wiki/PipelinesGitHub) template.
The step *Az CLI Deploy Management Groups* succeeded, but the next step - *Deploy Custom Policy Definitions* - fails with the error "The policy set definition 'Deploy-Diagnostics-x' request is invalid.

Full error message:
```
Run azure/arm-deploy@v1
  with:
    scope: managementgroup
    managementGroupId: con
    region: westeurope
    template: infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep
    parameters: infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json
    deploymentName: create_policy_defs-3
    failOnStdErr: false
  env:
    ManagementGroupPrefix: con
    TopLevelManagementGroupDisplayName: Contoso
    Location: westeurope
    LoggingSubId: ***
    LoggingResourceGroupName: alz-logging
    HubNetworkSubId: 2d88df96-b1fc-422d-a47d-eb9018284dc1
    HubNetworkResourceGroupName: hub-networking
    RoleAssignmentManagementGroupId: alz-platform
    SpokeNetworkSubId: 57e14e5c-cd9a-4a8d-9575-f39835f3048c
    SpokeNetworkResourceGroupName: spoke_networking
    runNumber: 3
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Validating template...
Warning: WARNING: /home/runner/work/msftdemo/msftdemo/infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep(1,1) : Info Bicep Linter Configuration: Custom bicepconfig.json file found (/home/runner/work/msftdemo/msftdemo/infra-as-code/bicep/modules/policy/definitions/bicepconfig.json).
/home/runner/work/msftdemo/msftdemo/infra-as-code/bicep/CRML/customerUsageAttribution/cuaIdManagementGroup.bicep(1,1) : Info Bicep Linter Configuration: Custom bicepconfig.json file found (/home/runner/work/msftdemo/msftdemo/infra-as-code/bicep/CRML/customerUsageAttribution/bicepconfig.json).

Creating deployment...
Error: WARNING: /home/runner/work/msftdemo/msftdemo/infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep(1,1) : Info Bicep Linter Configuration: Custom bicepconfig.json file found (/home/runner/work/msftdemo/msftdemo/infra-as-code/bicep/modules/policy/definitions/bicepconfig.json).
/home/runner/work/msftdemo/msftdemo/infra-as-code/bicep/CRML/customerUsageAttribution/cuaIdManagementGroup.bicep(1,1) : Info Bicep Linter Configuration: Custom bicepconfig.json file found (/home/runner/work/msftdemo/msftdemo/infra-as-code/bicep/CRML/customerUsageAttribution/bicepconfig.json).

Error: ERROR: ***"status":"Failed","error":***"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[***"code":"BadRequest","message":"***\r\n  \"error\": ***\r\n    \"code\": \"InvalidCreatePolicySetDefinitionRequest\",\r\n    \"message\": \"The policy set definition 'Deploy-MDFC-Config' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-ASC-SecurityContacts'.\"\r\n  ***\r\n***"***,***"code":"BadRequest","message":"***\r\n  \"error\": ***\r\n    \"code\": \"InvalidCreatePolicySetDefinitionRequest\",\r\n    \"message\": \"The policy set definition 'Deploy-Diagnostics-LogAnalytics' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Diagnostics-ACI,Deploy-Diagnostics-ACR,Deploy-Diagnostics-AnalysisService,Deploy-Diagnostics-ApiForFHIR,Deploy-Diagnostics-APIMgmt,Deploy-Diagnostics-ApplicationGateway,Deploy-Diagnostics-WebServerFarm,Deploy-Diagnostics-Website,Deploy-Diagnostics-AA,Deploy-Diagnostics-AVDScalingPlans,Deploy-Diagnostics-Bastion,Deploy-Diagnostics-CDNEndpoints,Deploy-Diagnostics-CognitiveServices,Deploy-Diagnostics-CosmosDB,Deploy-Diagnostics-Databricks,Deploy-Diagnostics-DataExplorerCluster,Deploy-Diagnostics-DataFactory,Deploy-Diagnostics-DLAnalytics,Deploy-Diagnostics-EventGridSub,Deploy-Diagnostics-EventGridTopic,Deploy-Diagnostics-EventGridSystemTopic,Deploy-Diagnostics-ExpressRoute,Deploy-Diagnostics-Firewall,Deploy-Diagnostics-FrontDoor,Deploy-Diagnostics-Function,Deploy-Diagnostics-HDInsight,Deploy-Diagnostics-iotHub,Deploy-Diagnostics-LoadBalancer,Deploy-Diagnostics-LogicAppsISE,Deploy-Diagnostics-MariaDB,Deploy-Diagnostics-MediaService,Deploy-Diagnostics-MlWorkspace,Deploy-Diagnostics-MySQL,Deploy-Diagnostics-NIC,Deploy-Diagnostics-NetworkSecurityGroups,Deploy-Diagnostics-PostgreSQL,Deploy-Diagnostics-PowerBIEmbedded,Deploy-Diagnostics-RedisCache,Deploy-Diagnostics-Relay,Deploy-Diagnostics-SignalR,Deploy-Diagnostics-SQLElasticPools,Deploy-Diagnostics-SQLMI,Deploy-Diagnostics-TimeSeriesInsights,Deploy-Diagnostics-TrafficManager,Deploy-Diagnostics-VM,Deploy-Diagnostics-VirtualNetwork,Deploy-Diagnostics-VMSS,Deploy-Diagnostics-VNetGW,Deploy-Diagnostics-WVDAppGroup,Deploy-Diagnostics-WVDHostPools,Deploy-Diagnostics-WVDWorkspace'.\"\r\n  ***\r\n***"***,***"code":"BadRequest","message":"***\r\n  \"error\": ***\r\n    \"code\": \"InvalidCreatePolicySetDefinitionRequest\",\r\n    \"message\": \"The policy set definition 'Enforce-EncryptTransit' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deny-AppServiceApiApp-http,Append-AppService-httpsonly,Append-AppService-latestTLS,Deny-AppServiceFunctionApp-http,Deploy-MySQL-sslEnforcement,Deny-MySql-http,Deploy-PostgreSQL-sslEnforcement,Deny-PostgreSql-http,Deny-Redis-http,Append-Redis-disableNonSslPort,Append-Redis-sslEnforcement,Deploy-SqlMi-minTLS,Deny-SqlMi-minTLS,Deploy-SQL-minTLS,Deny-Sql-minTLS,Deploy-Storage-sslEnforcement,Deny-Storage-minTLS,Deny-AppServiceWebApp-http'.\"\r\n  ***\r\n***"***,***"code":"BadRequest","message":"***\r\n  \"error\": ***\r\n    \"code\": \"InvalidCreatePolicySetDefinitionRequest\",\r\n    \"message\": \"The policy set definition 'Deploy-Sql-Security' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Sql-AuditingSettings,Deploy-Sql-SecurityAlertPolicies,Deploy-Sql-Tde,Deploy-Sql-vulnerabilityAssessments'.\"\r\n  ***\r\n***"***]***

Error: Deployment failed.
```

## To Reproduce

Create a GitHub Actions workflow based on the below code (update subscription IDs and make sure to create a secret called AZURE_CREDENTIALS):

```
name: ALZ GitHub Actions deployment pipeline

on: [workflow_dispatch]

env:
  ManagementGroupPrefix: "con"
  TopLevelManagementGroupDisplayName: "Contoso"
  Location: "westeurope"
  LoggingSubId: "1d6ec85d-73c1-44ac-afa4-d2586c91abb6"
  LoggingResourceGroupName: "alz-logging"
  HubNetworkSubId: "2d88df96-b1fc-422d-a47d-eb9018284dc1"
  HubNetworkResourceGroupName: "hub-networking"
  RoleAssignmentManagementGroupId: "alz-platform"
  SpokeNetworkSubId: "57e14e5c-cd9a-4a8d-9575-f39835f3048c"
  SpokeNetworkResourceGroupName: "spoke_networking"
  runNumber: ${{ github.run_number }}

jobs:
  bicep_tenant_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'janegilring/ALZ-Bicep'
          ref: 'msft-demo-contoso'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Az CLI Deploy Management Groups
        id: create_mgs
        shell: bash
        run: |
            az deployment tenant create --template-file infra-as-code/bicep/modules/managementGroups/managementGroups.bicep --parameters parTopLevelManagementGroupPrefix=${{ env.ManagementGroupPrefix }} parTopLevelManagementGroupDisplayName="${{ env.TopLevelManagementGroupDisplayName }}" --location ${{ env.Location }} --name create_mgs-${{ env.runNumber }}

      - name: Deploy Custom Policy Definitions
        id: create_policy_defs
        uses: azure/arm-deploy@v1
        with:
          scope: managementgroup
          managementGroupId: ${{ env.ManagementGroupPrefix }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep
          parameters: infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json
          deploymentName: create_policy_defs-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Custom Role Definitions
        id: create_rbac_roles
        uses: azure/arm-deploy@v1
        with:
          scope: managementgroup
          managementGroupId: ${{ env.ManagementGroupPrefix }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep
          parameters: infra-as-code/bicep/modules/customRoleDefinitions/parameters/customRoleDefinitions.parameters.all.json
          deploymentName: create_rbac_roles-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Logging Resource Group
        id: create_logging_rg
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.LoggingSubId }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
          parameters: parResourceGroupName=${{ env.LoggingResourceGroupName }} parLocation=${{ env.Location }}
          deploymentName: create_logging_rg-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Logging
        id: create_logging
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.LoggingSubId }}
          resourceGroupName: ${{ env.LoggingResourceGroupName }}
          template: infra-as-code/bicep/modules/logging/logging.bicep
          parameters: infra-as-code/bicep/modules/logging/parameters/logging.parameters.all.json
          deploymentName: create_logging-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Hub Networking Resource Group
        id: create_hub_network_rg
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.HubNetworkSubId }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
          parameters: parResourceGroupName=${{ env.HubNetworkResourceGroupName }} parLocation=${{ env.Location }}
          deploymentName: create_hub_network_rg-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Hub Network
        id: create_hub_network
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.HubNetworkSubId }}
          resourceGroupName: ${{ env.HubNetworkResourceGroupName }}
          template: infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
          parameters: infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.all.json
          deploymentName: create_hub_network-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Role Assignment
        id: create_role_assignment
        uses: azure/arm-deploy@v1
        with:
          scope: managementgroup
          managementGroupId: ${{ env.RoleAssignmentManagementGroupId }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
          parameters: infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroup.servicePrincipal.parameters.all.json
          deploymentName: create_role_assignment-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Subscription Placement
        id: create_subscription_placement
        uses: azure/arm-deploy@v1
        with:
          scope: managementgroup
          managementGroupId: ${{ env.ManagementGroupPrefix }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep
          parameters: infra-as-code/bicep/modules/subscriptionPlacement/parameters/subscriptionPlacement.parameters.all.json
          deploymentName: create_subscription_placement-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Default Policy Assignments
        id: create_policy_assignments
        uses: azure/arm-deploy@v1
        with:
          scope: managementgroup
          managementGroupId: ${{ env.ManagementGroupPrefix }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
          parameters: infra-as-code/bicep/modules/policy/assignments/alzDefaults/parameters/alzDefaultPolicyAssignments.parameters.all.json
          deploymentName: create_policy_assignments-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Spoke Networking Resource Group
        id: create_spoke_network_rg
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.SpokeNetworkSubId }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
          parameters: parResourceGroupName=${{ env.SpokeNetworkResourceGroupName }} parLocation=${{ env.Location }}
          deploymentName: create_spoke_network_rg-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Spoke Network
        id: create_spoke_network
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SpokeNetworkSubId }}
          resourceGroupName: ${{ env.SpokeNetworkResourceGroupName }}
          template: infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep
          parameters: infra-as-code/bicep/modules/spokeNetworking/parameters/spokeNetworking.parameters.all.json
          deploymentName: create_spoke_network-${{ env.runNumber }}
          failOnStdErr: false
```

## Expected behaviour

Deploy Custom Policy Definitions should succeed without any errors 🙂

## Screenshots 📷

![image](https://user-images.githubusercontent.com/2039662/204102978-d1784d1e-28dd-45dc-95b4-d920a835e020.png)

![image](https://user-images.githubusercontent.com/2039662/204103018-68181830-60bc-46e2-9ca0-e857b984df8b.png)

## Correlation ID

f01bcae4-7a6a-4d31-97d7-00a713328bd9

## Additional context

N/A
