### ISSUE TITLE
🪲 Bug Report - DDoS Network Protection Enabled by default even after turning it too false

### ISSUE THREAD

**Issue by FallenHoot** [Azure/ALZ-Bicep#408]
## Describe the bug

When deploying ALZ-Bicep with hub/spoke model. I noticed that even turning off (disabling) DDoS Network Protection from its default enabled/on setting. That it actually deployed DDoS Network Protection (DDoS Standard). 
```
@sys.description('Switch to enable/disable DDoS Network Protection deployment. Default: true')
param parDdosEnabled bool = false
```

## To Reproduce

Steps to reproduce the behaviour:

1. Deploy ALZ-Bicep with Hub/Spoke Model ( `param parDdosEnabled bool = false` (hubNetworking.bicep))
2. Do not turn it off in the hubNetworking.parameters.all.json nor hubNetworking.parameters.min.json 

## Expected behaviour

Shouldn't deploy a 3K USD service. 

## Screenshots 📷
![image](https://user-images.githubusercontent.com/19664186/205247120-d6d731de-7223-459f-8451-6f454a956bac.png)

## Correlation ID

5dc5e5fd-1622-4a5f-9dee-538817264260

## Additional context

I would advise to not even have this turned on by default as it is a 3,000 USD service and 1,500 USD if turned off before end of month. If you wish to opt into it, then you can turn it from disabled (false) to enabled (true).

**Comment by jtracey93** [comment]
Hey @FallenHoot,

Can you advise what commands you are using to deploy the hub networking module?

Are you also using the parameter file?

Let us know so we can try and repro. 

Thanks

**Comment by FallenHoot** [comment]
After thinking about it more. I was definitely in the wrong, by not changing the parameter file to `false` as well to avoid my confusion of looking at over 100 of files. In turn costing a heavy price tag. I would still advise to have this `false` in the scripts by default.

It is less of a bug more of a human error, but now a feature request. 

```
- name: Deploy Hub Network
        id: create_hub_network
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.HubNetworkSubId }}
          resourceGroupName: ${{ env.HubNetworkResourceGroupName }}
          template: infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
          parameters: infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.all.json
          deploymentName: create_hub_network-${{ env.runNumber }}
          failOnStdErr: false
```
