### ISSUE TITLE
How to deploy custom policy assigment?

### ISSUE THREAD

**Issue by kedar-1** [Azure/ALZ-Bicep#549]
Hello,

thanks for this project, it will help us to follow ALZ concept with using IaaC.
We are using Accelerator for initial deployment.

There is an assigment to deny deploy to not allowed locations - uksouth.

How can I adapt parameters file to deploy a assigment with set of location: westeurope, northeurope.

Following the Wiki I'm not able to understand what must be changed.

Thanks

**Comment by jtracey93** [comment]
Hey @kedar-1,

No worries at all.

Firstly, the assignment `.json` file for [`Deny-Resource-Locations`](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_deny_resource_locations.tmpl.json) is not actually assigned by default to the ALZ Management Group hierarchy as per: [aka.ms/alz/policy](aka.ms/alz/policy).

But you can certainly assign it by following an approach as [documented here](https://github.com/Azure/ALZ-Bicep/wiki/AssigningPolicies) I'd suggest option 2 personally if using the accelerator as per the [accelerator guidance here](https://github.com/Azure/ALZ-Bicep/wiki/Accelerator#incorporating-modified-alz-modules)

### High Level Steps

1. Copy [`alzDefaultPolicyAssignments.bicep`](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep) into `custom-modules` directory in your accelerator created repo
2. Amend the copied module to make the assignment you wish to make [`Deny-Resource-Locations`](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_deny_resource_locations.tmpl.json) following the [guidance here](https://github.com/Azure/ALZ-Bicep/wiki/AssigningPolicies#what-about-if-i-want-to-follow-option-2)
3. (Optionally) create and associated parameters file for your new module in the `custom-parameters` directory in your accelerator created repo
4. Amend the workflow [`alz-bicep-2.yml`](https://github.com/Azure/ALZ-Bicep/blob/main/accelerator/.github/workflows/alz-bicep-2.yml#L54-L59) amending lines: 8 + copy 58 to deploy your new module with your custom assignment by calling the [PowerShell script that the step calls ](https://github.com/Azure/ALZ-Bicep/blob/main/accelerator/pipeline-scripts/Deploy-ALZPolicyAssignments.ps1) again 

The modified step starting on line 54in the workflow will need to look something like this:
```yaml
- name: "Built-in and Custom Policy Assignments Deployment"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZPolicyAssignments.ps1
            .\pipeline-scripts\Deploy-ALZPolicyAssignments.ps1 -$TemplateFile "upstream-releases\$($env:UPSTREAM_RELEASE_VERSION)\infra-as-code\bicep\modules\policy\assignments\alzDefaults\alzDefaultPolicyAssignments.bicep" -$TemplateParameterFile "config\custom-parameters\<YOUR_CUSTOM_PARAMETER_FILE_FOR_THE_MODULE_YOU_CREATE>.parameters.all.json"
          azPSVersion: "latest"
``` 

This should get you working 👌

Let us know

cc: @oZakari
